export enum KeyCode {
  KeyA = "KeyA",
  KeyB = "KeyB",
  KeyC = "KeyC",
  KeyD = "KeyD",
  KeyE = "KeyE",
  KeyF = "KeyF",
  KeyG = "KeyG",
  KeyH = "KeyH",
  KeyI = "KeyI",
  KeyJ = "KeyJ",
  KeyK = "KeyK",
  KeyL = "KeyL",
  KeyM = "KeyM",
  KeyN = "KeyN",
  KeyO = "KeyO",
  KeyP = "KeyP",
  KeyQ = "KeyQ",
  KeyR = "KeyR",
  KeyS = "KeyS",
  KeyT = "KeyT",
  KeyU = "KeyU",
  KeyV = "KeyV",
  KeyW = "KeyW",
  KeyX = "KeyX",
  KeyY = "KeyY",
  KeyZ = "KeyZ",

  Escape = "Escape",
  F1 = "F1",
  F2 = "F2",
  F3 = "F3",
  F4 = "F4",
  F5 = "F5",
  F6 = "F6",
  F7 = "F7",
  F8 = "F8",
  F9 = "F9",
  F10 = "F10",

  Backquote = "Backquote",
  Digit1 = "Digit1",
  Digit2 = "Digit2",
  Digit3 = "Digit3",
  Digit4 = "Digit4",
  Digit5 = "Digit5",
  Digit6 = "Digit6",
  Digit7 = "Digit7",
  Digit8 = "Digit8",
  Digit9 = "Digit9",
  Digit0 = "Digit0",
  Minus = "Minus",
  Equal = "Equal",
  Space = "Space",
  Backspace = "Backspace",

  Tab = "Tab",
  CapsLock = "CapsLock",

  BracketLeft = "BracketLeft",
  BracketRight = "BracketRight",
  Backslash = "Backslash",
  Semicolon = "Semicolon",
  Quote = "Quote",
  Comma = "Comma",
  Period = "Period",
  Slash = "Slash",

  Shift = "Shift",
  ShiftLeft = "ShiftLeft",
  ShiftRight = "ShiftRight",
  Control = "Control",
  ControlLeft = "ControlLeft",
  ControlRight = "ControlRight",
  Alt = "Alt",
  AltLeft = "AltLeft",
  AltRight = "AltRight",

  Delete = "Delete",
  Insert = "Insert",
  PageUp = "PageUp",
  PageDown = "PageDown",
  Pause = "Pause",
  End = "End",

  ArrowUp = "ArrowUp",
  ArrowLeft = "ArrowLeft",
  ArrowDown = "ArrowDown",
  ArrowRight = "ArrowRight",

  NumLock = "NumLock",
  Numpad1 = "Numpad1",
  Numpad2 = "Numpad2",
  Numpad3 = "Numpad3",
  Numpad4 = "Numpad4",
  Numpad5 = "Numpad5",
  Numpad6 = "Numpad6",
  Numpad7 = "Numpad7",
  Numpad8 = "Numpad8",
  Numpad9 = "Numpad9",
  Numpad0 = "Numpad0",
  NumpadDecimal = "NumpadDecimal",
}

// alias
export enum KeyCode {
  A = KeyA,
  B = KeyB,
  C = KeyC,
  D = KeyD,
  E = KeyE,
  F = KeyF,
  G = KeyG,
  H = KeyH,
  I = KeyI,
  J = KeyJ,
  K = KeyK,
  L = KeyL,
  M = KeyM,
  N = KeyN,
  O = KeyO,
  P = KeyP,
  Q = KeyQ,
  R = KeyR,
  S = KeyS,
  T = KeyT,
  U = KeyU,
  V = KeyV,
  W = KeyW,
  X = KeyX,
  Y = KeyY,
  Z = KeyZ,
}
